#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: e2e-tests

# Run on every push, and allow it to be run manually.
on: [push, workflow_dispatch]

permissions: read-all

jobs:
  e2e-tests:
    # Skip if running in a fork that might not have secrets configured.
    if: ${{ github.repository == 'sigstore/cosign' }}
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0
      - uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
        with:
          go-version: '1.18'
          check-latest: true
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@877d4953d2c70a0ba7ef3290ae968eb24af233bb # v0.5.1
        with:
          project_id: projectsigstore
          service_account_key: ${{ secrets.GCP_CI_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Set up `crane`
        run: go install github.com/google/go-containerregistry/cmd/crane@v0.8.0
      - name: gcloud auth configure-docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Run e2e_test_secrets.sh
        shell: bash
        run: ./test/e2e_test_secrets.sh
