# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test GitHub OIDC
on:
  push:
    branches: [ 'main', 'release-*' ]
  schedule:
    - cron: '0 1 * * *' # 1AM UTC
  workflow_dispatch:

jobs:
  build:
    permissions:
      id-token: write
      packages: write
      contents: read
    env:
      COSIGN_EXPERIMENTAL: "true"
      GIT_HASH: ${{ github.sha }}
      GIT_VERSION: unstable
      GITHUB_RUN_ID: ${{ github.run_id }}
      GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
      KO_PREFIX: ghcr.io/${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.17.x'

      # Install tools.
      - uses: sigstore/cosign-installer@bb61838e7ee5bf314f85f2e219b3706835fa6306 # v2.0.1
      - uses: imjasonh/setup-ko@2c3450ca27f6e6f2b02e72a40f2163c281a1f675 # v0.4

      - name: Build and sign a container image
        run: |
          set -e
          # Build and publish an image.
          make sign-keyless-container

      - name: Build and sign a blob
        run: |
          set -e
          make cosign
          make sign-blob-experimental
