#
# Copyright 2021 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CI-Validate-Release-Job

on:
  push:
    branches:
      - main
      - release-*
  pull_request:

jobs:
  check-signature:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sigstore/cosign/cosign:v2.4.0-dev@sha256:a97b592b9f73390edcd6ceb5799a62513a906cbdffcdc63f53585910c71b0708

    steps:
      - name: Check Signature
        run: |
          cosign verify ghcr.io/gythialy/golang-cross:v1.22.6-0@sha256:34ba9945085680b8966b78929e3520478ec9ea38a315fa13d8d5e0ce6355d0d2 \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity "https://github.com/gythialy/golang-cross/.github/workflows/release-golang-cross.yml@refs/tags/v1.22.6-0"
        env:
          TUF_ROOT: /tmp

  validate-release-job:
    runs-on: ubuntu-latest
    needs:
      - check-signature

    container:
      image: ghcr.io/gythialy/golang-cross:v1.22.6-0@sha256:34ba9945085680b8966b78929e3520478ec9ea38a315fa13d8d5e0ce6355d0d2
      volumes:
        - /usr:/host_usr
        - /opt:/host_opt

    permissions: {}

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # Error: fatal: detected dubious ownership in repository at '/__w/cosign/cosign'
      #      To add an exception for this directory, call:
      #          git config --system --add safe.directory /__w/cosign/cosign
      # Reason: Recent versions of git require the .git folder to be owned
      # by the same user (see https://github.blog/2022-04-12-git-security-vulnerability-announced/).
      # Related
      # - https://github.com/actions/runner/issues/2033
      # - https://github.com/actions/checkout/issues/1048
      # - https://github.com/actions/runner-images/issues/6775
      - run: git config --system --add safe.directory /__w/cosign/cosign

      # Related to https://github.com/sigstore/cosign/issues/3149
      # note this runs from within the golang-cross container, so if we want to free up space
      # on the host, we have to reach through the bind mounts to clean up unused content on the runners
      - name: free up disk space for the release
        run: |
          rm -rf /host_usr/share/dotnet || true
          rm -rf /host_usr/share/swift || true
          rm -rf /host_usr/local/lib/android || true
          rm -rf /host_usr/local/.ghcup || true
          rm -rf /host_usr/local/graalvm/ || true
          rm -rf /host_usr/local/share/powershell || true
          rm -rf /host_usr/local/share/chromium || true
          rm -rf /host_usr/local/lib/node_modules || true
          rm -rf /host_usr/lib/google-cloud-sdk || true
          rm -rf /host_usr/local/share/boost || true
          rm -rf /host_opt/hostedtoolcache/ || true
          rm -rf /host_opt/ghc || true
      - name: check disk space
        run: df -h

      - name: goreleaser snapshot
        run: make snapshot
        env:
          PROJECT_ID: honk-fake-project
          RUNTIME_IMAGE: gcr.io/distroless/static-debian12:nonroot

      - name: check binaries
        run: |
          ./dist/cosign-linux-amd64 version
